### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by deinemutteer** [dwatring/Memo-Calendar#16]
Which login credentials do I have to use to login at the login frame and where can i set them?

**Comment by dwatring** [comment]
Hey! This project is rather old, but if you'd like to employ your own version, you must set up your own database and connect it to the project. 

To do this, change these variables in the "DBConnect.java" file to match your own database config:
- hostname
- port
- dbUsername
- dbPassword 
- dbName

https://www.db4free.net/ provides free MySQL databases for private use. Hope this helps!
